### ISSUE TITLE
13th AGE sheet

### ISSUE THREAD

**Issue by jimgonoid** [neovatar/roll20-character-sheets#4]
Hi, i'm new in roll20.
I think the 13th age character sheet has an issue in the backgrounds macro. It takes the base stat not the modifier.

Where i can see how the macro is made.. i see a lot of 0s and /2 in the macro and i do not understand.

**Comment by neovatar** [comment]
You can find the formula in 13th_Age-neovatar.html lines 596-601 (click on "raw" view in github to see the complete lines):

https://github.com/neovatar/roll20-character-sheets/blob/13th_Age-neovatar/13th_Age-neovatar/13th_Age-neovatar.html#L596-L601

Depending on the chosen ability, a formula is selected. As you see all background formulas in 13_Age-neovatar.html are identical except for the ability mod.

The numbers you see in Roll20 when doing a roll are a little confusing. If you hover over a background check result in Roll20, you see something like the following:

````Rolling 1d20+(floor((14+0+0)/2)-5)+1+4 = 15+(floor((14+0+0)/2)-5)+1+4````

Let's walk through this: On the left side of  ````=```` you see the roll formula Roll20 will calculate. On the right side you see the formula after the roll.

Roll20 does not store the readily calculated value of your ability modificator but the formula used to derive the ability mod. Instead of the calculated mod you see ````floor((14+0+0)/2)-5```` (in this example the ability value is ````14```` and thus should yield an mod of ````2````). This output is a little bit confusing, but that's how Roll20 works.

So reading the right side in this example: The roll is ````15```` (its the ````1d20```` from the left side), then the ability mod is added (````floor((14+0+0)/2)-5```` totaling to ````2````), followed by the characters level (````1````) and the number of points in this background (````4````).

I did a quick check of the background formulas and they work correctly for me.

**Comment by jimgonoid** [comment]
Thanks for the help.

Now i understand.  
Great Work.

One more thing, when i have 2 or 3 dice in one icon relationship, the result are added. The solution was to have one row per dice.
